apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-django-app
spec:
  replicas: 3 # Adjust the number of replicas as needed
template:
  metadata:
    labels:
      app: my-django-app
  spec:
    containers:
    - name: my-django-app
      image: my-django-app:latest
      ports:
      - containerPort: 8000 # Adjust the port as per your Django app

apiVersion: v1
kind: Service
metadata:
  name: my-django-app-service
spec:
  selector:
    app: my-django-app
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 8000 # Container port
  type: LoadBalancer