apiVersion: apps/v1
kind: Deployment
metadata:
  name: task
spec:
  replicas: 3 # Adjust the number of replicas as needed
template:
  metadata:
    labels:
      app: task
  spec:
    containers:
    - name: task
      image: task:latest
      ports:
      - containerPort: 8000 # Adjust the port as per your Django app

apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  selector:
    app: task
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 8000 # Container port
  type: LoadBalancer